### ISSUE TITLE
Testing https://github.com/mambax7/oledrion / xoops 2.5.9 - cannot see / add gateways

### ISSUE THREAD

**Issue by rossbcan** [mambax7/oledrion#1]
Downloaded from https://github.com/mambax7/oledrion
Configuration Check
Minimum PHP required: 5.5 (your version is 5.5.38)
MYSQL Minimum version required: 5.5 (your version is 5.5.60)
Minimum XOOPS required: 2.5.9 (your version is 2.5.9)
Minimum ModuleAdmin required: 1.2 (your version is 1.2)

/home/e-smith/files/ibays/rossco/html/uploads/oledrion ( Available. )
/home/e-smith/files/ibays/rossco/html/uploads/oledrion/attached ( Available. )
/home/e-smith/files/ibays/rossco/html/uploads/oledrion/images ( Available. )
/home/e-smith/files/ibays/rossco/html/uploads/oledrion/cvs ( Available. )
/home/e-smith/files/ibays/rossco/html/uploads/oledrion/cache/ ( Available. )
/home/e-smith/files/ibays/rossco/html/uploads/oledrion/text/ ( Available. )

Problem #1: Classname error:
define('OLEDRION_GATEWAY_PATH', XOOPS_ROOT_PATH . '/modules/' . $moduleDirName . '/class/Gateways' . '/'); (modules/oledrion/include/common.php) - else "file not found"

modules/oledrion/admin/index.php?op=gateways
Starting with fresh install: cannot see option to add gateway or standard gateways.
Import oledrion DB from working 2.5.7 system: cannot see any gateways.

debug: no errors

If I uninstall module and install modified 2.34 from working system (the changes proposed), all OK

Mamba: Think we need to collaborate on this. You should be able to install on a 2.5.9 system and observe the same as I.

Suspect issues related to your 2.5.9 major re-org, classnames...

To be clear: Problem persists after fixing classname error above.

Regards;
Bill

**Comment by mambax7** [comment]
Please check the latest update, I hope, it will fix now the Gateway issue.
Thanks for testing and reporting the bugs...
There is still a lot of refactoring needed, but with your help, hopefully we'll get there soon...

**Comment by rossbcan** [comment]
Hi Michael;

 

Unable to install oledrion. Error(s):

Installing eCommerce

 

Duplicate column name 'skip_packing'

 

modules/oledrion/sql/mysql.sql:

  `skip_packing`            TINYINT(1)            NOT NULL DEFAULT '0',

  `skip_location`           TINYINT(1)            NOT NULL DEFAULT '0',

  `skip_delivery`           TINYINT(1)            NOT NULL DEFAULT '0',

 

Multiple definitions of above. After fixed:

 

A problem has occurred on our server!

Page is currently unavailable

 

Warning: constant(): Couldn't find constant OLEDRION_UPLOAD_PATH in file /modules/oledrion/include/config.php line 34

Warning: constant(): Couldn't find constant OLEDRION_UPLOAD_PATH in file /modules/oledrion/include/config.php line 35

Warning: constant(): Couldn't find constant OLEDRION_UPLOAD_PATH in file /modules/oledrion/include/config.php line 36

Warning: constant(): Couldn't find constant OLEDRION_UPLOAD_PATH in file /modules/oledrion/include/config.php line 40

Warning: constant(): Couldn't find constant OLEDRION_UPLOAD_PATH in file /modules/oledrion/include/config.php line 41

Warning: constant(): Couldn't find constant OLEDRION_UPLOAD_PATH in file /modules/oledrion/include/config.php line 42

Warning: constant(): Couldn't find constant OLEDRION_AUTHOR_LOGOIMG in file /modules/oledrion/include/config.php line 80

Warning: mkdir(): No such file or directory in file /modules/oledrion/class/Common/FilesManagement.php line 33

Error: RuntimeException: Unable to create the directory in file /modules/oledrion/class/Common/FilesManagement.php line 34

 

This seems to be due to XOOPS_UPLOAD_PATH undefined. It is defined on “include/defines.php” (not included), with a warning:” YOU SHOULD AVOID USING THE FOLLOWING CONSTANTS, THEY WILL BE REMOVED”

 

Not sure how you want to handle this…

Regards;

Bill

**Comment by mambax7** [comment]
That's not good :( 
Let me check these issues. I'll keep you posted....

**Comment by mambax7** [comment]
OK, this should be now fixed. Please test and let me know. 
If you find problems, please open a new incident, so then we can track it better,  and also link it to the Pull Request. 
Once again, thanks for testing and bug reporting!
