### ISSUE TITLE
Failed to execute xoops_module_pre_install_oledrion

### ISSUE THREAD

**Issue by rossbcan** [mambax7/oledrion#2]
$modversion['version']             = 2.35;
$modversion['module_status']       = 'Beta  2';
$modversion['release_date']        = '2018/07/08';

Warning: constant(): Couldn't find constant CO_OLEDRION_ERROR_BAD_PHP in file /modules/oledrion/class/Common/VersionChecks.php line 72

tail /var/log/messages:
php-cgi: PHP Fatal error:  Call to a member function getVar() on a non-object in modules/oledrion/xoops_version.php on line 365

**Comment by mambax7** [comment]
Try the newer version that I've uploaded yesterday, or you can just change the line 365 yourself like this here:
https://github.com/mambax7/oledrion/commit/6e2d2cc00e540573ead6055f16e682940691f90c

**Comment by rossbcan** [comment]
Hi Michael;

 

Line 365 is already:

if (is_object($xoopsModule) && $xoopsModule->getVar('isactive') && $xoopsModule->getVar('dirname') == $modversion['dirname']) {

 

I downloaded the new version this AM, prior to reporting bug.

 

Regards;

Bill

**Comment by mambax7** [comment]
This is because you're using an obsolete version of PHP :( 
The module is checking if you have a minimum of PHP 5.6, and it fails because you have PHP 5.5

Got to xoops_version.php and modify the PHP requirement to this:
```php
$modversion['min_php']             = '5.5';
```

And try to install it again. 

And get away from PHP 5.5 :)

**Comment by mambax7** [comment]
Once you install it, you can go to Preferences, and set the "Show Sample Button?" to yes, and save it.
![image](https://user-images.githubusercontent.com/613686/42454930-df041400-835e-11e8-8d82-0ce69de37fd3.png)

Then in the Admin click on the "Import Sample Data"
![image](https://user-images.githubusercontent.com/613686/42455001-08576578-835f-11e8-9d2d-055dd2713e8d.png)

And Oledrion will get populated with sample data, which should make your testing easier.

**Comment by rossbcan** [comment]
Updated PHP:

 

*	Minimum PHP required: 5.6 (your version is 5.6.36) 
MYSQL Minimum version required: 5.5 (your version is 5.5.60)
Minimum XOOPS required: 2.5.9 (your version is 2.5.9) 
Minimum ModuleAdmin required: 1.2 (your version is 1.2) 

/home/e-smith/files/ibays/rossco/html/uploads/oledrion ( Available. ) 
/home/e-smith/files/ibays/rossco/html/uploads/oledrion/attached ( Available. ) 
/home/e-smith/files/ibays/rossco/html/uploads/oledrion/images ( Available. ) 
/home/e-smith/files/ibays/rossco/html/uploads/oledrion/cvs ( Available. ) 
/home/e-smith/files/ibays/rossco/html/uploads/oledrion/cache/ ( Available. ) 
/home/e-smith/files/ibays/rossco/html/uploads/oledrion/text/ ( Available. )

 

Installed properly. IMHO, problem still exists if wrong php version (error not handled gracefully).

 

Imported (phpmyadmin) my oledrion DB.

Can see (and edit) gateways

 

When attempt to checkout:

Notice: Use of undefined constant OLEDRION_CONFIRMATION_EMAIL_FILENAME_SUFFIX - assumed 'OLEDRION_CONFIRMATION_EMAIL_FILENAME_SUFFIX' in file /modules/oledrion/checkout.php line 685 (why is this reported undefined?)

Notice: Undefined variable: h_oledrion_payment in file /modules/oledrion/checkout.php line 706 (U probably made this a class var)

 

Regards;

Bill

**Comment by mambax7** [comment]
Notices are not a problem in this stage of testing. Please let me know if you were able to check out and if the check-out process was working. I'm not a Paypal expert, so any help here using the sandbox would be very helpful. 

BTW - I just updated another module yesterday that provides a paid subscription, but again, I don't know if the Paypal intergration works there, so if you want to test it, please do:
https://github.com/mambax7/subscription

**Comment by rossbcan** [comment]
Hi Michael;

 

I checkout by:

wget https://github.com/XoopsModules25x/oledrion/archive/master.zip

 

…which seems to be working. Haven’t tried git clone. What, exactly would you like me to test regarding checkout?

 

This is definitely a problem:

Notice: Undefined variable: h_oledrion_payment in file /modules/oledrion/checkout.php line 706 (U probably made this a class var)

 

I cannot proceed paypal testing without it. Casualty of class re-org

 

For now, will stick with existing module. Have zero issues doing paypal testing. Will test subscription module once we pass current module.

Do you want some pointers for paypal testing? Their site is pretty clear regarding sandbox setup…. In fact, may want to (eventually) have a default oledrion sandbox as part of oledrion, or at least a howto. 

 

If there are going to be further modules requiring payment, long term, may want a common payment module for core. 

 

Regards;

Bill

**Comment by mambax7** [comment]
please rename $h_oledrion_payment to $paymentHandler in:
line 706 in  \oledrion\checkout.php

**Comment by mambax7** [comment]
That's why it would be better to use the current version, otherwise it will be hard to integrate any changes you might do to the old version, because the "$h_oledrion_payment" variable was used in the old version and it was part of your changes that I've added to the current version.
It's just a good investment to focus on one version :)

**Comment by rossbcan** [comment]
Hi Michael;

 

Error, impossible to find the country list from the gateway

None All Errors (1) Deprecated (0) Queries (40) Blocks (0) Extra (2) Timers(5)

Errors

Notice: Use of undefined constant OLEDRION_CONFIRMATION_EMAIL_FILENAME_SUFFIX - assumed 'OLEDRION_CONFIRMATION_EMAIL_FILENAME_SUFFIX' in file /modules/oledrion/checkout.php line 685

 

Because $gateway is NULL in line 718, oledrion\checkout.php

 

Suspect payment_gateway not being set

 

Regards;

Bill

**Comment by mambax7** [comment]
Where exactly do you see the issue? When I go to checkout, I can select the country as here:

![image](https://user-images.githubusercontent.com/613686/42482957-b08e69fe-83b8-11e8-9d8f-3a085d8d7623.png)

**Comment by mambax7** [comment]
The problem with OLEDRION_CONFIRMATION_EMAIL_FILENAME_SUFFIX was that you've added it to /config.php, while it should be in /include/common.php

The repository has been updated now

**Comment by rossbcan** [comment]
Error, impossible to find the country list from the gateway
Happens after paypal is selected for payment, selecting "Final Confirm":

![image](https://user-images.githubusercontent.com/13289915/42502926-4d4b2b3c-8405-11e8-9d75-3c37227ce671.png)

In file modules/oledrion/checkout.php, line 718 ($gateway == NULL)

$gateway = \XoopsModules\Oledrion\Gateways::getGatewayObject($payment->getVar('payment_gateway'));
var_dump($gateway);
if (!is_object($gateway)) {
     die(_OLEDRION_ERROR20);
}

something wrong with gateway class. Maybe clue: "Paypal" versus "paypal" in DB (payment_gateway)

Original version:
![image](https://user-images.githubusercontent.com/13289915/42503350-70ab57b8-8406-11e8-9046-ff3fc897fdbb.png)

New version:
![image](https://user-images.githubusercontent.com/13289915/42503505-d4b67d5a-8406-11e8-96b9-8767e3513dea.png)

**Comment by mambax7** [comment]
Can you then change in your database the "paypal" to "Paypal"  in the column "payment_gateway" to see if this make any difference?

**Comment by rossbcan** [comment]
Original is "paypal", New is "Paypal". Changing to "paypal", no effect (same error).

I know you are not setup for Paypal, so, its up to me. Please suggest some tests that will help to narrow down why "$gateway = \XoopsModules\Oledrion\Gateways::getGatewayObject($payment->getVar('payment_gateway'));" is failing.

Alternatively, I can (offline) provide Paypal sandbox account creds, or, help you to create account.

**Comment by rossbcan** [comment]
Note that this may be related to my TODO hack at checkout.php:705, where I was unable to determine how to select payment_id from array of gateways, so, I select the first. This also needs to be addressed.

**Comment by mambax7** [comment]
OK, I'll check it out, and I'll keep you posted. 
In the future, to make sure that we're testing with the same data set, you will be able to export your data and email me the YML files.  They will be located in the /testdata folder in a folder "Exports"+timestamp. 
![image](https://user-images.githubusercontent.com/613686/42508869-1074221e-8418-11e8-8b0d-e8b2fd4ae5ed.png)
This feature has been improved and is now uploaded.

**Comment by rossbcan** [comment]
Even with bogus paypal creds, U should see this error

**Comment by mambax7** [comment]
This should be now fixed in https://github.com/mambax7/oledrion/releases/tag/2.35_Beta-3

**Comment by rossbcan** [comment]
Well done. Prelim results (beta-3, will test more)

![image](https://user-images.githubusercontent.com/13289915/42567136-cc16d264-84d6-11e8-8b7b-1dbf58a6e62c.png)

**Comment by mambax7** [comment]
Happy to hear it! 👍
